mdmasharafilhossain/HireMaster-Client

src/Comonents/ExploreByCategory/ExploreByCategory.jsx
src/Pages/Home/Home.jsx

This is explore by category section where people can explore their desire category.

created explore-by-category section for homepage

---

src/Comonents/ExploreByCategory/ExploreByCategory.jsx

we select a new color for our project and i updated my code with the new color.

color changed as requirement

---

src/Comonents/Navbar/Navbar.jsx
src/Pages/Home/Banner/Banner.jsx

initialization of responsive header with drawer

[feature](header_responsive):responsive header with drawer

---

src/Comonents/Navbar/Navbar.jsx
src/Comonents/Routes/Routes.jsx
src/Pages/Jobs/JobCard.jsx
src/Pages/Jobs/Jobs.jsx

initial jobs page and component

[feature](jobs):jobs page initialization

---

package-lock.json
package.json
src/Pages/ContactUs/ContactUs.jsx

email js integration for user message

[feature](contact_us):email js integration for user message

---

src/Comonents/Testimonial/Testimonials.jsx
src/Comonents/Testimonial/pagination.css

[feature](testimonial):redesign of testimonials

---

src/Pages/ContactUs/ContactUs.jsx
src/Pages/Jobs/Jobs.jsx

filtering job with title and job time

[feature](jobs_filter):filtering job with title and job time

---

src/Pages/Profile/Profile.jsx

user profile section updated 

---

package-lock.json
package.json
src/Comonents/ProfileNav/ProfileNav.jsx
src/Comonents/UserProfileForm/UserProfileForm.jsx
src/Pages/Profile/Profile.jsx
src/main.jsx

Fixed some issue of our user profile section.

fixed some issue

---

package-lock.json
package.json
src/Comonents/JobFilter/JobFilter.jsx
src/Comonents/JobList/SingleJobList.jsx
src/Comonents/Navbar/Navbar2.jsx
src/Comonents/Routes/PrivateRoute.jsx
src/Pages/JobDetails/JobDetails.jsx
src/Pages/Jobs/Jobs.jsx
src/Pages/Login/Login.jsx
src/Pages/SignUp/SignUp.jsx

user login/reg error log with jobs design retouch

user login/reg error log with jobs design retouch

---

src/Comonents/Footer/Footer.jsx
src/Comonents/Hooks/UseAxiosPublic/UseAxiosPublic.jsx
src/Comonents/JobFilter/JobFilter.jsx
src/Comonents/JobList/SingleJobList.jsx
src/Pages/Jobs/Jobs.jsx

updated jobs page for design also footer rearrange

updated jobs page also footer rearrange

---

src/Pages/Education/Education.jsx

solved the bug of profile page

---

src/Pages/Education/Education.jsx

solved bug of profile page.

---

src/Comonents/Navbar/Navbar.jsx
src/Comonents/Navbar/Navbar2.jsx
src/Pages/About/About.jsx
src/Pages/ContactUs/ContactUs.jsx
src/Pages/Jobs/Jobs.jsx
src/Pages/Jobs/MyJobs.jsx
src/Pages/Login/Login.jsx
src/Pages/SignUp/SignUp.jsx
src/Pages/Signup2/ManagerLogin.jsx
src/Pages/Signup2/ManagerSignup.jsx
src/Pages/Signup2/Signup2.jsx
src/api/index.js

second navbar customization and placement in routes

second navbar customization and placement in routes

---

src/Comonents/Navbar/Navbar.jsx
src/Comonents/Routes/PrivateRoute.jsx
src/Comonents/Routes/Routes.jsx
src/Pages/Profile/ManagerProfile.jsx
src/Pages/Signup2/Signup2.jsx

Routing-related bug fixed and manager profile logout route created.

[BugFixed]

---

src/AdminDashboard/AllTechNews/AdminTechNews.jsx
src/Comonents/Navbar/Navbar.jsx
src/api/index.js

pagination implementation in admin all  news

pagination implementation in admin all  news

---

package-lock.json
src/Comonents/Hooks/useJobCategory/useJobCategory.jsx
src/Comonents/UserProfileForm/UserProfileForm.jsx
src/Pages/Education/Education.jsx
src/Pages/Experience/Experience.jsx
src/Pages/Profile/Profile.jsx
src/Pages/Profile/ProfileImage.jsx
src/Pages/ProfileHead/ProfileHead.jsx
src/Pages/Projects/Projects.jsx

added image update functionality

added image update functionality 

---

package-lock.json
src/Comonents/ExploreByCategory/ExploreByCategory.jsx
src/Comonents/Hooks/Notifications/getNotifications.jsx
src/Comonents/JobFilter/JobFilter.jsx
src/Comonents/JobList/SingleJobList.jsx
src/Comonents/Navbar/Navbar2.jsx
src/Comonents/Payment/PaymentHomeCard/PaymentHomeCard.jsx
src/Comonents/Routes/Routes.jsx
src/Comonents/Testimonial/Testimonials.jsx
src/Comonents/ThemeChange/Theme.jsx
src/Comonents/UserProfileForm/UserProfileForm.jsx
src/LayOut/MainLayOut.jsx
src/Pages/About/About.jsx
src/Pages/Appliedjobs/Appliedjobs.jsx
src/Pages/Appliedjobs/SingleAppliedJobs.jsx
src/Pages/JobDetails/JobDetails.jsx
src/Pages/JobFair/JobFairProfile.jsx
src/Pages/Jobs/Jobs.jsx
src/Pages/Login/Login.jsx
src/Pages/Profile/Profile.jsx
src/Pages/SignUp/SignUp.jsx
src/Pages/Signup2/ManagerLogin.jsx
src/Pages/Signup2/ManagerSignup.jsx
src/api/index.js
tailwind.config.js

notifications, toggle password, light and dark theme, forget password implemented

Miran ibrahim notification feature

---

public/category.json

solved some bugs

---

README.md
src/Comonents/ExploreByCategory/ExploreByCategoryCard.jsx
src/Pages/JobPost/JobPost.jsx

solved some bugs and make some changes

solved some bugs and make some changes

---

README.md

make some changes in README.md file

make some changes in README.md file

---

README.md

make some changes in README.md

make some changes in README.md
